name: build

on:
  push:
    branches: [ "main", "github_actions" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_qt:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2

      - name: Install qt
        uses: jurplel/install-qt-action@v3.2.1
        with:
          version: '6.4.3'
          dir: 'C:/'

      - name: Build
        run: |
          cmake . -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-O3 -mwindows"
          cmake --build . --target Mega_calcApp 

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: Mega Calc App
          path: .
          retention-days: 5