name: build

on:
  push:
    branches: [ "main", "github_actions" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_qt:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2

      - name: Install qt
        uses: jurplel/install-qt-action@v3.2.1
        with:
          dir: 'C:/'
          aqtversion: '==3.1.*'
          version: '6.4.3'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_mingw'

      - name: Build
        run: |
          mkdir cmake-build-release-mingw-for-qt
          cd cmake-build-release-mingw-for-qt
          cmake -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-O3 -mwindows" -B ..
          cmake --build . --target Mega_calcApp -j 10 

      - name: Create installer
        uses: nadeemjazmawe/inno-setup-action-cli@v6.0.5
        with:
            filepath: './installer/setup.iss'

      - name: Upload installer
        uses: actions/upload-artifact@v3.1.2
        with:
          name: Mega Calc App
          path: ./installer/Setup.exe
          retention-days: 5